// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo3u34pR2nZKO7yIac-Z-AfaS9vFYut5s',
    appId: '1:713085086615:android:77a63e0bef89ba3c89b2d2',
    messagingSenderId: '713085086615',
    projectId: 'home-maintenance-app-c2dd1',
    databaseURL: 'https://home-maintenance-app-c2dd1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'home-maintenance-app-c2dd1.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeRtIyo0USMCoy6IjqzaRxX0ddwJfcLSk',
    appId: '1:713085086615:web:3bf05c0dde4a7d3789b2d2',
    messagingSenderId: '713085086615',
    projectId: 'home-maintenance-app-c2dd1',
    authDomain: 'home-maintenance-app-c2dd1.firebaseapp.com',
    databaseURL: 'https://home-maintenance-app-c2dd1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'home-maintenance-app-c2dd1.firebasestorage.app',
    measurementId: 'G-1N8P2X9WXB',
  );
}
